version: '3'
services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    networks:
      - location-extractor
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: backend
    networks:
      - location-extractor
    ports:
      - "8000:8000"
    env_file:
      - .env

networks:
  location-extractor:
    driver: bridge
